### ISSUE TITLE
Create a Music Player App 

### ISSUE THREAD

**Issue by SayanGuha04** [Sbiswas001/JavaScript-Apps#12]
**Is your feature request related to a problem? Please describe.**
Create a music player app using HTML, CSS and JavaScript 

**Describe the solution you'd like**
https://www.youtube.com/watch?v=JtrFzoL1joI&list=PLjwm_8O3suyOgDS_Z8AWbbq3zpCmR-WE9&index=10&pp=iAQB

**Comment by Rupankarsaha** [comment]
assign to me
