### ISSUE TITLE
Create a Calculator App

### ISSUE THREAD

**Issue by SayanGuha04** [Sbiswas001/JavaScript-Apps#14]
**Is your feature request related to a problem? Please describe.**
Create a calculator app using HTML, CSS and JavaScript

**Describe the solution you'd like**
https://www.youtube.com/watch?v=cGgLHJGyS34&list=PLjwm_8O3suyOgDS_Z8AWbbq3zpCmR-WE9&index=12&pp=iAQB

**Comment by T1050** [comment]
Please assign this to me
