### ISSUE TITLE
Create Age Calculator App

### ISSUE THREAD

**Issue by Sbiswas001** [Sbiswas001/JavaScript-Apps#6]
**Is your feature request related to a problem? Please describe.**
Make an age calculator app using JavaScript

**Describe the solution you'd like**
https://www.youtube.com/watch?v=_pw8vk1tAhs&list=PLjwm_8O3suyOgDS_Z8AWbbq3zpCmR-WE9&index=6&pp=iAQB

**Comment by SayanGuha04** [comment]
Please assign this task to me
