### ISSUE TITLE
Create Mini Calendar App

### ISSUE THREAD

**Issue by Sbiswas001** [Sbiswas001/JavaScript-Apps#9]
**Is your feature request related to a problem? Please describe.**
Use JavaScript

**Describe the solution you'd like**
https://www.youtube.com/watch?v=b6473PrT-dU&list=PLjwm_8O3suyOgDS_Z8AWbbq3zpCmR-WE9&index=23&pp=iAQB

**Comment by SouravM1** [comment]
Please assign this to me.
